### PR TITLE
reciving call

### PR DESCRIPTION
**Pull request by SzymonSalamon**
adding reciving call and message incoming call from

### CODE REVIEW

**Review by DamianMizera — APPROVED** [review]
Looks good to me

**Comment by Bartosz-Slowik** [comment]
Please rebase/ resolve conflicts from new main branch. Its a small conflict.

**Comment by SzymonSalamon** [comment]
> Please rebase/ resolve conflicts from new main branch. Its a small conflict.

Done

**Review by DamianMizera — APPROVED** [review]
Good resolve. Approve

**Review by Bartosz-Slowik — APPROVED** [review]
good fix

**Pull request merged**
