### PR TITLE
adding call drop feature

### PR DESCRIPTION
**Pull request by DamianMizera**

### CODE REVIEW

**Comment by DamianMizera** [comment]
[Dropping Call](https://trello.com/c/0fp2o34H/8-dropping-call)

**Review by SzymonSalamon — COMMENTED** [review]
lgtm

**Review by SzymonSalamon — APPROVED** [review]

**Comment by Bartosz-Slowik** [comment]
Need to resolve problems from Szymon push.

**Comment by DamianMizera** [comment]
conflicts resolved

**Review by Bartosz-Slowik — APPROVED** [review]
good

**Pull request merged**
