### PR TITLE
My fork did not iclude all commits for some reason. CI test.

### PR DESCRIPTION
**Pull request by Bartosz-Slowik**

### CODE REVIEW

**Comment by Bartosz-Slowik** [comment]
Aprove my PR so i can merge

**Review by SzymonSalamon — COMMENTED** [review]
COOL

**Comment by pawel00wypych** [comment]
cool

**Review by pawel00wypych — APPROVED** [review]
all correct

**Review by SzymonSalamon — APPROVED** [review]

**Pull request merged**
