### PR TITLE
Attach basics from lab1

### PR DESCRIPTION
**Pull request by Bartosz-Slowik**
Comment any suggestions you might have.

### CODE REVIEW

**Review by SzymonSalamon — APPROVED** [review]
Looks good to me. I'm not sure with stopTimer() and change state order because on diargram UML in documentation it's revers but in my point of view better first stop timer and next change State.

**Review by pawel00wypych — APPROVED** [review]
good job

**Review by DamianMizera — APPROVED** [review]
Cool

**Comment by Bartosz-Slowik** [comment]
> Looks good to me. I'm not sure with stopTimer() and change state order because on diargram UML in documentation it's revers but in my point of view better first stop timer and next change State.

I think the order does not matter too much but this order ensures that the timer does not run out during the function

**Pull request merged**
