### PR TITLE
Sending call request

### PR DESCRIPTION
**Pull request by pawel00wypych**

### CODE REVIEW

**Comment by Bartosz-Slowik** [comment]
Please next time try splitting PR to a smaller ones.
 Its hard to read 1k+ lines of code that does many functionalities.

**Review by Bartosz-Slowik — APPROVED** [review]
Big progress

**Review by DamianMizera — APPROVED** [review]
Looks good to me, read attribute is redundant, but my commit will rewrite this part.

**Review by SzymonSalamon — CHANGES_REQUESTED** [review]
Next time split review. One feature one review it will be easier to review and understand for us.

**Comment by pawel00wypych** [comment]
code quickfix done

**Review by SzymonSalamon — APPROVED** [review]

**Pull request merged**
